---


- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  become: true


- name: Install Splunk
  include_tasks: install_splunk.yml


- name: Bypass first-time UI login
  include_tasks: bypass_first_ui_login.yml


- name: Set Splunk secret
  include_tasks: set_splunk_secret.yml


- name: Configure adminstrative user
  include_tasks: configure_administrative_user.yml


- name: Configure Splunk OS user
  include_tasks: configure_splunk_os_user.yml


- name: Configure Splunk service
  include_tasks: configure_splunk_service.yml


- name: Start Splunk
  include_tasks: start_splunk.yml
