---
# file: .../tasks/set_splunk_secret.yml


- name: Set Splunk secret
  copy:
    dest: "{{ __splunk_home | default('/opt/splunk') }}/etc/auth/splunk.secret"
    owner: "{{ __splunk_user | default('splunk') }}"
    group: "{{ __splunk_group | default('splunk') }}"
    mode: 0600
    content: "{{ __splunk_secret | string | regex_escape }}"
  become: true
  when:
    - __splunk_secret is defined
