---
dependency:
  name: galaxy
  options:
    role-file: full_cluster_requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance-cluster-master
    box: generic/rhel7
    groups:
      - splunk_servers
      - splunk_cluster_masters
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
  - name: instance-deployment-server
    box: generic/rhel7
    groups:
      - splunk_servers
      - splunk_deployment_servers
  - name: instance-cluster-search-head-deployer
    box: generic/rhel7
    groups:
      - splunk_servers
      - splunk_search_head_deployers
  - name: instance-cluster-indexer-1
    box: generic/rhel7
    groups:
      - splunk_servers
      - splunk_indexers
  - name: instance-cluster-indexer-2
    box: generic/rhel7
    groups:
      - splunk_servers
      - splunk_indexers
  - name: instance-cluster-indexer-3
    box: generic/rhel7
    groups:
      - splunk_servers
      - splunk_indexers
  - name: instance-cluster-search-head-1
    box: generic/rhel7
    groups:
      - splunk_servers
      - splunk_search_heads
  - name: instance-cluster-search-head-2
    box: generic/rhel7
    groups:
      - splunk_servers
      - splunk_search_heads
  - name: instance-cluster-search-head-3
    box: generic/rhel7
    groups:
      - splunk_servers
      - splunk_search_heads
provisioner:
  name: ansible
  config_options:
    defaults:
      vault_identity_list: '~/.vault_password,~/.atlas_it_shared_vault_secret'
  inventory:
    host_vars:
      rhel8-instance:
        ansible_python_interpreter: /usr/libexec/platform-python
  lint:
    name: ansible-lint
    options:
      x: ['204', '301']
verifier:
  name: testinfra
  lint:
    name: flake8
